services:
  api:
    build: .
    container_name: api_catalogocamafeu
    ports:
      - "54850:54850"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=development
    dns:
      - 8.8.8.8
      - 1.1.1.1
volumes:
  pgdata:
